config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'splash#index'

  resources :groups, only: %i[index new create] do
    resources :purchases, only: %i[index new create]
  end

  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :purchases

  validates :name, :icon, :user, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :author_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases
  has_many :groups

  validates :name, presence: true, allow_blank: false, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  def authenticate_user!
    return if user_signed_in? || (controller_name == 'splash' && action_name == 'index')

    super
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || groups_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.includes(:purchases)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  def index
    @purchases = @group.purchases.order(created_at: :desc)
    @total_amount = @purchases.sum(:amount)
  end

  def new
    @purchase = @group.purchases.build
  end

  def create
    @purchase = @group.purchases.new(purchase_params)
    @purchase.author_id = current_user.id

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to group_purchases_path(@group), notice: 'Transaction was successfully created.' }
      else
        format.html { render :new }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('new_purchase', partial: 'purchases/form',
                                                                    locals: { purchase: @purchase })
        end
      end
    end
  end

  private

  def set_group
    @group = current_user.groups.includes(:purchases).find(params[:group_id])
  end

  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  layout 'splash'

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_out_user
    sign_out(current_user)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/groups/_form.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-3xl text-center font-semibold mb-4" style="color: #434b54;">New Category</h1>

  <%= form_for(@group) do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation" class="bg-red-100 p-4 mb-4 rounded">
        <h2 class="text-red-800"><%= pluralize(@group.errors.count, 'error') %> blocked this category from being saved:</h2>

        <ul class="list-disc list-inside mt-2">
          <% @group.errors.full_messages.each do |message| %>
            <li class="text-red-600"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= f.label :name, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="mb-4">
      <%= f.label :icon, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.text_field :icon, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

  <div class="mt-8 p-2 rounded text-center" style="background-color: #5fb523;">
    <div class="w-90 mx-auto">
      <%= f.submit 'Create Category', class: 'text-white font-semibold py-4 px-4 border border-white rounded transition duration-300 ease-in-out hover:bg-white hover:text-green-500 block w-full' %>
    </div>
  </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="container mx-auto mt-8 bg-slate-100">
  <h1 class="text-3xl text-center font-semibold mb-4" style="color: #434b54;">Categories</h1>

  <div class="grid grid-cols-1 md:grid-cols-1 lg:grid-cols-1 gap-4">
    <% @groups.each do |group| %>
      <div class="bg-white p-6 rounded-lg shadow-md mb-4">
        <div class="flex items-center justify-between mb-2">
          <div class="flex items-center">
            <img src=<%=group.icon%> class="images"  alt="icon-picture" width="80" height="80">
            <h2 class="text-xl text-gray-600/50 font-semibold ml-4"><%= group.name %></h2>
          </div>
          <p class="font-semibold" style="color: #434b54;">$<%= group.purchases.sum(:amount) %></p>
        </div>
        <%= link_to 'View Transactions', group_purchases_path(group), class: 'text-blue-500 block mt-2' %>
      </div>
    <% end %>
  </div>

  <div class="mt-8 p-2 rounded text-center" style="background-color: #5fb523;">
    <div class="w-90 mx-auto">
      <%= link_to 'Add a new category', new_group_path, class: 'text-white font-semibold py-4 px-4 border border-white rounded transition duration-300 ease-in-out hover:bg-white hover:text-green-500 block w-full' %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<% content_for :additional_links do %>
  <a href="<%= groups_path %>" class="text-lg text-white"><i class="fas fa-arrow-left"></i></a>
<% end %>
<%= render 'form', group: @group %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-proxima-nova@1.0.1/style.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/9e6b5903a6.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="font-family: 'Proxima Nova', sans-serif;">
  <%= render 'shared/navbar' %>
  <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetApp - Splash</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-proxima-nova@1.0.1/style.min.css">
  <script src="https://cdn.tailwindcss.com"></script>
  <%= javascript_importmap_tags %>
</head>
<body style="font-family: 'Proxima Nova', sans-serif;">
  <%= yield %>
</body>
</html>

app/views/purchases/_form.html.erb
<div class="container mx-auto mt-8 text-center">
  <h1 class="text-3xl font-semibold mb-6" style="color: #434b54;">Add a new transaction for <%= @group.name %></h1>

  <%= form_for([@group, @purchase], html: { class: 'max-w-md mx-auto' }) do |f| %>
    <% if @purchase.errors.any? %>
      <div id="error_explanation" class="mb-4">
        <h2 class="text-red-500"><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>
        <ul class="list-disc list-inside text-left text-red-500">
          <% @purchase.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= f.label :name, class: 'block text-gray-600 text-md' %>
      <%= f.text_field :name, class: 'w-full border rounded-md p-2', placeholder: 'Transaction Name' %>
    </div>

    <div class="mb-4">
      <%= f.label :amount, class: 'block text-gray-600 text-md' %>
      <%= f.number_field :amount, class: 'w-full border rounded-md p-2', placeholder: 'Amount (USD)' %>
    </div>

    <div class="mb-6">
      <div class="mt-8 p-2 rounded text-center" style="background-color: #5fb523;">
        <div class="w-90 mx-auto">
          <%= f.submit 'Create Transaction', class: 'text-white font-semibold py-4 px-4 border border-white rounded transition duration-300 ease-in-out hover:bg-white hover:text-green-500 block w-full' %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/purchases/index.html.erb
<% content_for :additional_links do %>
  <a href="<%= groups_path %>" class="text-lg text-white"><i class="fas fa-arrow-left"></i></a>
<% end %>
<div class="container mx-auto mt-8 text-center">
  <h1 class="text-3xl font-semibold mb-6" style="color: #434b54;">Transactions for <%= @group.name %></h1>

  <div class="mb-6">
    <p class="text-gray-600 font-semibold mb-6">Total Amount: $<%= @total_amount %></p>
    <div class="mt-8 p-2 rounded text-center" style="background-color: #5fb523;">
      <div class="w-90 mx-auto">
        <%= link_to 'Add a new transaction', new_group_purchase_path(@group), class: 'text-white font-semibold py-4 px-4 border border-white rounded transition duration-300 ease-in-out hover:bg-white hover:text-green-500 block w-full' %>
      </div>
    </div>
  </div>

  <% @purchases.each do |purchase| %>
    <div class="bg-white rounded-lg shadow-md mb-8">
      <div class="flex justify-between items-center p-6">
        <h3 class="text-xl font-semibold"><%= purchase.name %></h3>
        <p class="text-green-500 font-semibold">Amount: $<%= purchase.amount %></p>
      </div>
      <div class="text-center p-6 bg-gray-100">
        <p class="text-gray-600">Created at: <%= purchase.created_at %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/purchases/new.html.erb
<% content_for :additional_links do %>
  <a href="<%= group_purchases_path(@group) %>" class="text-lg text-white"><i class="fas fa-arrow-left"></i></a>
<% end %>

<%= render 'form', purchase: @purchase %>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
  <header class="p-4 text-white flex justify-between items-center" style="background-color: #377ac2;">
    <%= image_tag('Budget-App.png', alt: 'Budget App', class: 'h-6 md:h-8 lg:h-10 xl:h-12') %>
    <%= yield :additional_links %>
    <%= link_to 'Logout', sign_out_user_path, method: :get, class: 'text-white' %>    
  </header>
<% end %>

app/views/shared/_navbar.html.erb
<% unless user_signed_in? %>
<nav class="flex justify-between navbar" style="background-color: #377ac2; color: white; padding: 1rem;">
  <a href="<%= root_path %>" class="text-lg text-white"><i class="fas fa-arrow-left"></i></a>
  <%= yield :navbar_links %>
</nav>
<% end %>

app/views/splash/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget app</title>
</head>
<body>
 <section class="splash-section flex justify-center items-center h-[100vh]">
    <div class="splash-container w-[100%] flex flex-col">
        <div class="title-container h-[60vh] flex items-center justify-center">
        <h2 class="text-center text-3xl font-semibold splash-title">Budget App</h2>
    </div>
    <div class="log-in-container flex flex-col w-[80%] mx-auto mt-16">
        <%= link_to "LOG IN", new_user_session_path, class: 'px-3 py-2 text-center btn my-2 hover:bg-blue-500 hover:text-white' %>
        <%= link_to "SIGN UP", new_user_registration_path, class: 'px-3 py-2 text-center text-gray-500 btn2 hover:bg-blue-500 hover:text-white' %>
    </div>
    </div>   
  </section>
</body>
</html>